name: ppi_gnn_linux
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - torchvision=0.20.1
  - pyg::pytorch-geometric=2.6.1
  - numpy=2.0.2
  - pandas=2.3.1
  - scipy=1.13.1
  - scikit-learn=1.6.1
  - matplotlib=3.9.4
  - networkx=3.2.1
  - tqdm=4.67.1
  - tensorboardx=2.6.2.2
  - pyyaml=6.0.2
  - pip
  - pip:
      - argparse==1.4.0
